version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: waste-management-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: waste_management_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/sample_data.sql:/docker-entrypoint-initdb.d/2-sample_data.sql
    networks:
      - waste-management-network

  backend:
    build: .
    container_name: waste-management-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/waste_management_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - waste-management-network

volumes:
  mysql_data:

networks:
  waste-management-network:
    driver: bridge
