spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bintobloom?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:bintobloom_user}
    password: ${DB_PASSWORD:secure_password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    show-sql: false

  security:
    require-ssl: false

jwt:
  secret: ${JWT_SECRET:myVerySecureSecretKeyForProductionUse123456789}
  expiration: 86400000 # 24 hours

logging:
  level:
    com.bintobloom: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/bintobloom.log

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
